---

- name: Update repositories
  apt:
    update_cache: yes
  sudo: yes

- name: Ensure ruby, lynis and ansi2html is installed using apt
  apt:
    pkg:
      - ruby
      - ruby-dev
      - build-essential
      - libffi-dev
      - make
      - lynis
      - kbtin
    state: present