---

- name: Update repositories
  apt:
    update_cache: yes

- name: Ensure ruby, lynis and ansi2html is installed using apt
  apt:
    pkg:
      - ruby
      - ruby1.9.1-dev
      - build-essential
      - libffi-dev
      - lynis
      - kbtin
    state: present