---

# For RedHat, Ubuntu, and macOS
- name: Install inspec 
  raw: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec 

#- name: export env variable to automate inspec license accepting
#  raw: export CHEF_LICENSE=accept-no-persist

- name: Check patch installation on linux box
  command: inspec exec --chef-license accept-silent https://github.com/dev-sec/linux-patch-baseline
  check_mode: yes

- name: Check OS Hardening on linux box
  command: inspec exec --chef-license accept-silent https://github.com/dev-sec/linux-baseline
