---

# For RedHat, Ubuntu, and macOS
- name: Install inspec 
  raw: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec 

- name: Update repositories
  apt:
    update_cache: yes
    
- name: Install ansi2html
  apt:
    name: kbtin

- name: Check patch installation on linux box
  raw: inspec exec --chef-license accept-silent https://github.com/dev-sec/linux-patch-baseline | ansi2html -la > report-linux-patch-baseline.html
  register: command_result
  ignore_errors: True

- name: Check OS Hardening on linux box
  command: inspec exec --chef-license accept-silent https://github.com/dev-sec/linux-baseline | ansi2html -la > report-linux-oshardening-baseline.html
  check_mode: yes
