---

# For RedHat, Ubuntu, and macOS
- name: Install inspec 
  raw: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec 

- name: export env variable to automate inspec license accepting
  command: export CHEF_LICENSE=accept-no-persist

- name: Check patch installation on linux box
  command: inspec exec https://github.com/dev-sec/linux-patch-baseline

- name: Check OS Hardening on linux box
  command: inspec exec https://github.com/dev-sec/linux-baseline
