---

- name: Update repositories
  yum:
    update_cache: yes

- name: Ensure ruby, lynis and ansi2html is installed using yum
  yum:
    pkg:
      - ruby
      - ruby-dev
      - build-essential
      - libffi-dev
      - lynis
      - kbtin
    state: present