---

- name: Mail sending using Ansible mail module
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "madhupinc@gmail.com"
    password: "ikummikrgfkdeqat"
    to: "User <madhupcool@gmail.com>"
    subject: "hey, its ansible"
    body: "Iron Man is back"
    attach: /home/ubuntu/report-linux-patch-baseline.html /home/ubuntu/report-linux-oshardening-baseline.html
    secure: starttls
