---
- hosts: all
  become: yes
  gather_facts: True
  vars_files:
    - group_vars/vars.yml

  vars:
    rack: "goldenAMI"

  roles:
    - { role: patchesUpdates, tags: ["patchesUpdates"], when: ansible_os_family != "Windows" }
    - { role: dev-sec.os-hardening, tags: ["dev-sec.os-hardening"], when: ansible_os_family != "Windows" }
    - { role: sshHardening, tags: ["sshHardening"], when: ansible_os_family != "Windows" }
    - { role: win-patchesUpdates, tags: ["win-patchesUpdates"], when: ansible_os_family == "Windows" }
    #- { role: dev-sec.windows-hardening, tags: ["dev-sec.windows-hardening"], when: ansible_os_family == "Windows"}



