---
- hosts: all
  become: yes
  gather_facts: True
  vars_files:
    - group_vars/vars.yml

  vars:
    rack: "goldenScannedAMI"

  roles:
    - { role: scanHardening, tags: ["scanHardening"] }
    - { role: email, tags: email }
